services:
  backend:
    build:
      context: ./tennant-middleware/backend
      target: dev
    container_name: tennant-middleware-dev
    image: tennant-middleware-dev
    ports:
      - 5000:8000
    env_file:
      - tennant-middleware/backend/.env
    volumes:
      - ./tennant-middleware/backend/src:/tennant-middleware/src
      - ./tennant-middleware/backend/tests:/tennant-middleware/tests
      - ./tennant-middleware/uvicorn/config.json:/tennant-middleware/uvicorn/config.json:ro
    command: [
      "uvicorn", "--factory", "src.main:create_app",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--reload",
      "--log-config", "uvicorn/config.json"
    ]
